[build]
  command = "npm run build:production"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "vite"
  command = "npm run dev"
  targetPort = 8080

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
